// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDetqU7dVRTofoijFNHLtQsZnutodmaHSI',
    appId: '1:332817763245:android:b35bef15b2036bee826f24',
    messagingSenderId: '332817763245',
    projectId: 'our-chat-f61c7',
    storageBucket: 'our-chat-f61c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMrqkmlgc0OZG-w1cnNIXAOj8qUqO884',
    appId: '1:332817763245:ios:20e3d79848db654f826f24',
    messagingSenderId: '332817763245',
    projectId: 'our-chat-f61c7',
    storageBucket: 'our-chat-f61c7.appspot.com',
    androidClientId: '332817763245-4cm61f1st197i7j8vm63tmdr6thgee17.apps.googleusercontent.com',
    iosClientId: '332817763245-l80alq5c8bvkn97urnlkcs11hhhde6v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApplicationFromYoutube',
  );
}
